name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: Copy file
      run: move target/release/cube_simulator.exe cube_simulator.exe
    - uses: actions/upload-artifact@v4
      with:
        name: cube simulator 3D
        path: |
          target/release/cube_simulator.exe
          assets
